### ISSUE TITLE
Easy way to add support for a new extension?

### ISSUE THREAD

**Issue by rrobison44** [0sawaqed/vscode-poweron#1]
Is there an easy way to add support for the ".POW" extension?  Thanks.

**Comment by BorisTK421** [comment]
@rrobison44 , were you able to add your extension? We have a similar issue. We use '.PN' since that was how we used PowerEditor. I tried adding it to the 'packages.json' file but it didn't seem to take.

**Comment by 0sawaqed** [comment]
### **You don’t have to modify anything to get this to work.** 

**1. Simply open the file with the new extension you want to register with Visual Studio, then press** `Ctrl` + `Shift` + `P` **and type `Change Language Mode`.**

![image](https://user-images.githubusercontent.com/62345757/163877814-8fc62a88-82b6-4330-af3c-0b38c155afbd.png)


**2. Then Select `Configure File Association for '.POW' ...`**

![image](https://user-images.githubusercontent.com/62345757/163877891-57b9757c-e61d-4b9c-91cf-e386e863eca9.png)


**3. Select `PowerOn` from the list of languages listed.**

![image](https://user-images.githubusercontent.com/62345757/163878017-ed4dda07-5be9-4596-a8b3-956f01561a92.png)


**4. Once you do that, Visual Studio will automatically detect any file with the extension `.POW` as a `PowerOn` language moving forward.**

![image](https://user-images.githubusercontent.com/62345757/163877359-39ee5740-cd7a-4838-80ac-f5a892af697d.png)

**Comment by rrobison44** [comment]
I was able to just add POW to package.json.  Then just had to reload.  But it is nice to see the correct way above :).  Thanks!

**Comment by BorisTK421** [comment]
Thank you for your help, that was perfect!

I'm sure you have been asked this a lot, but have you been able to get any
sort of debugging working? Or maybe a way to push it up to the sym like you
can do with the powereditor?
